project:
  type: website
  output-dir: docs

website:
  title: "Şadiye's Analytics Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: About Me
        href: about.qmd 
      - text: My Data Course Notes
        href: posts.qmd
      - text: "EMU430 Coursework"
        menu:
          - text: Assignments
            href: assignments.qmd 
          - text: Project
            href: project.qmd
            
    tools:
      - icon: github
        href: https://github.com/sadiye-1
      - icon: linkedin
        href: https://www.linkedin.com/in/%C5%9Fadiye-%C3%B6zt%C3%BCrk-ba711219a/

  sidebar:
    - title: "Assignments"
      style: "docked"
      search: true
      contents:
        - assignments.qmd
        - assignments/assignment-1.qmd
        - assignments/assignment-2.qmd  
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: minty
      dark: lux
    css: styles.css


editor: visual

